---
version: "2.1"
services:
  webtop:
    image: ghcr.io/decatoncheir/docker-webtop-ubuntu:latest
    container_name: docker-web-top-ubuntu
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Hong_Kong
#      - SUBFOLDER=/ #optional
#      - KEYBOARD=en-us-qwerty #optional
    volumes:
      - config:/config
#      - /var/run/docker.sock:/var/run/docker.sock #optional

    ports:
      - 3000:3000
#    devices:
#      - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped
    privileged: true
volumes:
  config: